---
##
# Apache
#
- name: "Add settings per ubuntu release"
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags:
   - apache

- name: Install packages.
  apt: pkg="{{ item }}" state=present
  with_items:
   - apache2
   # For htpasswd ansible module
   - python-passlib

- name: Enable modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
  notify: restart apache
  with_items: "{{ apache_modules_enable }}"

- name: Disable modules
  command: a2dismod {{ item }} removes=/etc/apache2/mods-enabled/{{ item }}.load
  notify: restart apache
  with_items: "{{ apache_modules_disable }}"

- name: Configure apache listen port
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ apache_listen_port }}"
  notify: restart apache

- name: Create htpasswd directory
  file: path={{ apache_conf_path }}/htpasswd/ state=directory

- name: Creating htpasswd entries
  copy:
    content: |
      {% for line in item.value %}
      {{ line }}
      {% endfor %}
    dest: "{{ apache_conf_path }}/htpasswd/{{ item.key }}"
    owner: root
    group: www-data
    mode: 0640
  with_dict: "{{ apache_htpasswd_files }}"
  notify: restart apache

- name: "Configure sites"
  include: configure_site.yml
  vars:
    site_name: "{{ item.key }}"
    site: "{{ apache_site_defaults|combine(item.value) }}"
  with_dict: "{{ apache_sites }}"

- name: "Remove old sites"
  include: remove_site.yml
  vars:
    site_name: "{{ item }}"
  with_items: "{{ apache_sites_absent }}"
